version: '3.8'
services:
  db:
    image: postgres
    restart: always
    user: postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - Dockerfile

  frontend:
    build: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      backend:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - Dockerfile
volumes:
  pgdata: